"""
Property-based tests for business logic payload generation.

# Feature: web-security-audit-toolkit, Property 17: Geração de payloads de manipulação de lógica de negócio

**Validates: Requirements 9.1**

Property under test
-------------------
``get_manipulation_payloads()`` returns **exactly** the fixed set of 5
business-logic manipulation values defined in Requirement 9.1:

    {-1, 0, 0.000000001, 9007199254740991, "abc"}

For any numeric parameter name, the set of values sent during a parameter
manipulation test is always exactly this fixed set — no more, no less.

Sub-properties verified:
  1. ``BUSINESS_LOGIC_PAYLOADS`` (via ``get_manipulation_payloads()``) is
     exactly the set ``{-1, 0, 0.000000001, 9007199254740991, "abc"}``.
  2. For any numeric parameter name (generated by Hypothesis), the payload
     set produced equals the same fixed set.
  3. Each individual expected payload is always present in the returned list.
  4. No extra payload values appear beyond the fixed set.
  5. The result always contains exactly 5 elements.
"""

from __future__ import annotations

import string

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from toolkit.execution.checks.business_logic import get_manipulation_payloads

# ---------------------------------------------------------------------------
# Expected fixed set (Req. 9.1 — Property 17)
# ---------------------------------------------------------------------------

EXPECTED_PAYLOADS: set = {-1, 0, 0.000000001, 9007199254740991, "abc"}

# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------

# Parameter names: any non-empty string of typical identifier characters
_param_name_strategy = st.text(
    alphabet=string.ascii_letters + string.digits + "_",
    min_size=1,
    max_size=64,
)


# ---------------------------------------------------------------------------
# Property 17 — fixed payload set identity
# ---------------------------------------------------------------------------


@given(param_name=_param_name_strategy)
@settings(max_examples=100)
def test_property17_payload_set_is_exactly_fixed_set(param_name: str) -> None:
    """
    Property 17: Geração de payloads de manipulação de lógica de negócio.

    **Validates: Requirements 9.1**

    For any numeric parameter name, ``get_manipulation_payloads()`` returns
    exactly the fixed set {-1, 0, 0.000000001, 9007199254740991, "abc"}.

    The ``param_name`` argument is accepted to make it explicit that the
    result is independent of the parameter being tested.
    """
    # The parameter name does not influence the returned payload set.
    payloads = get_manipulation_payloads()
    payload_set = set(payloads)

    assert payload_set == EXPECTED_PAYLOADS, (
        f"Payload set mismatch for param '{param_name}'.\n"
        f"  Expected : {EXPECTED_PAYLOADS!r}\n"
        f"  Actual   : {payload_set!r}\n"
        f"  Missing  : {EXPECTED_PAYLOADS - payload_set!r}\n"
        f"  Extra    : {payload_set - EXPECTED_PAYLOADS!r}"
    )


@given(param_name=_param_name_strategy)
@settings(max_examples=100)
def test_property17_payload_list_has_exactly_5_elements(param_name: str) -> None:
    """
    Property 17 (cardinality): Geração de payloads de manipulação de lógica de negócio.

    **Validates: Requirements 9.1**

    The list returned by ``get_manipulation_payloads()`` always contains
    exactly 5 elements, matching the 5 values defined in the specification.
    """
    payloads = get_manipulation_payloads()

    assert len(payloads) == 5, (
        f"Expected exactly 5 payloads for param '{param_name}', "
        f"got {len(payloads)}: {payloads!r}"
    )


@given(param_name=_param_name_strategy)
@settings(max_examples=100)
def test_property17_each_expected_payload_is_present(param_name: str) -> None:
    """
    Property 17 (membership): Geração de payloads de manipulação de lógica de negócio.

    **Validates: Requirements 9.1**

    Each of the 5 individually mandated values is present in the returned
    payload list, regardless of parameter name.
    """
    payloads = get_manipulation_payloads()
    payload_set = set(payloads)

    for expected_value in EXPECTED_PAYLOADS:
        assert expected_value in payload_set, (
            f"Required payload value {expected_value!r} missing "
            f"from result for param '{param_name}': {payloads!r}"
        )


@given(param_name=_param_name_strategy)
@settings(max_examples=100)
def test_property17_no_extra_payloads_beyond_fixed_set(param_name: str) -> None:
    """
    Property 17 (no extras): Geração de payloads de manipulação de lógica de negócio.

    **Validates: Requirements 9.1**

    The returned payload list must contain no values outside the fixed set.
    No undocumented or extra test values should be injected.
    """
    payloads = get_manipulation_payloads()
    payload_set = set(payloads)

    extra = payload_set - EXPECTED_PAYLOADS
    assert not extra, (
        f"Unexpected extra payloads found for param '{param_name}': {extra!r}"
    )


# ---------------------------------------------------------------------------
# Edge-case / determinism checks (non-PBT, always run)
# ---------------------------------------------------------------------------


def test_property17_returns_new_list_on_each_call() -> None:
    """
    ``get_manipulation_payloads()`` returns a new list instance on each call
    so that callers cannot accidentally mutate the internal state.
    """
    list_a = get_manipulation_payloads()
    list_b = get_manipulation_payloads()

    assert list_a is not list_b, (
        "get_manipulation_payloads() must return a new list on every call "
        "to prevent shared-state mutations."
    )


def test_property17_payload_set_equals_expected_set_directly() -> None:
    """
    Direct assertion: set(get_manipulation_payloads()) == EXPECTED_PAYLOADS.

    **Validates: Requirements 9.1**
    """
    assert set(get_manipulation_payloads()) == EXPECTED_PAYLOADS


def test_property17_negative_one_present() -> None:
    """The value -1 (negative integer) is in the payload list."""
    assert -1 in get_manipulation_payloads()


def test_property17_zero_present() -> None:
    """The value 0 (zero) is in the payload list."""
    assert 0 in get_manipulation_payloads()


def test_property17_extreme_fractional_present() -> None:
    """The value 0.000000001 (extreme fractional) is in the payload list."""
    assert 0.000000001 in get_manipulation_payloads()


def test_property17_max_safe_integer_present() -> None:
    """The value 9007199254740991 (max safe JS integer) is in the payload list."""
    assert 9007199254740991 in get_manipulation_payloads()


def test_property17_string_abc_present() -> None:
    """The value 'abc' (type-confusion string) is in the payload list."""
    assert "abc" in get_manipulation_payloads()
